[package]
name = "forensics"
version = "0.1.0"
edition = "2024"

[dependencies]
phf = { version = "0.11.*", features = ["macros"] }
rbx_dom_weak = "*"
ustr = "*"
clap = { version = "4.5.37", features = ["derive"] }
lz4 = "1.23.3"
zstd = "0.13.2"
